version: '3.8'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"  # Default edge port
      - "4571:4571"  # Legacy port for S3
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "${TMPDIR:-/06/localstack}:/06"
      - "/var/run/docker.sock:/var/run/docker.sock"